org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=lapisreservereborn
mod.name=Lapis Reserve Reborn
mod.group=dev.vesper
mod.version=1.0.17
#mod.channel_tag=-alpha.2
mod.authors=VesMaybeVesper
#mod.contributors=ContributorName, AnotherContributorName
mod.license=MIT
mod.description=Hold Lapis in Enchanting Tables
mod.sources_url=
mod.homepage_url=
mod.issues_url=
mod.discord_url=

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=EOBBpcat
publish.curseforge=
publish.github=true
